name: Docker Image CI

on:
  push:
    branches: [ dev ]

steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '16.13'
      cache: 'npm'
      cache-dependency-path: '**/package-lock.json'
  - run: npm install
  - run: npm run deploy

